# Generated by Django 4.2.3 on 2023-07-19 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_base_price', models.DecimalField(decimal_places=2, help_text='Rs', max_digits=10)),
                ('distance_base_price_upto', models.DecimalField(decimal_places=2, default=3, help_text='Km', max_digits=10)),
                ('distance_base_price_after_upto', models.DecimalField(decimal_places=2, default=90, help_text='Rs', max_digits=10)),
                ('distance_additional_price', models.DecimalField(decimal_places=2, help_text='Rs', max_digits=6)),
                ('distance_additional_price_upto', models.DecimalField(decimal_places=2, default=3, help_text='Km', max_digits=6)),
                ('distance_additional_price_after_upto', models.DecimalField(decimal_places=2, default=28, help_text='Rs', max_digits=6)),
                ('time_multiplier_factor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time_multiplier_factor_upto', models.DecimalField(decimal_places=2, default=1, help_text='hrs', max_digits=6)),
                ('time_multiplier_factor_after_upto', models.DecimalField(decimal_places=2, default=1.25, max_digits=6)),
                ('waiting_charges', models.DecimalField(decimal_places=2, help_text='Rs', max_digits=6)),
                ('waiting_charges_upto', models.DecimalField(decimal_places=2, default=3, help_text='mins', max_digits=6)),
                ('waiting_charges_after_upto', models.DecimalField(decimal_places=2, default=2, help_text='Rs per min', max_digits=6)),
                ('days_of_week', models.CharField(help_text='Comma-separated days (e.g., Mon,Tue)', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
